version: "3.7"
# https://docs.docker.com/compose/compose-file/

services:
######
# ActiveMQ setup
######
#  activemq:
#    image: rmohr/activemq:5.15.9-alpine
#    privileged: true
#    ports:
#      - "61616:61616"
#      - "8161:8161"
#      - "5672:5672"
#      - "61613:61613"
#      - "1883:1883"
#      - "61614:61614"
######
# Kafka setup
######
  zoo0:
    image: confluentinc/cp-zookeeper:6.1.4
    hostname: zoo0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka0:
    image: confluentinc/cp-kafka:6.1.4
    hostname: kafka0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka0:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: "zoo0:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
    depends_on:
      - zoo1
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8888:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka0:19092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zoo0:2181
    depends_on:
      - zoo0
      - kafka0
######
# RabbitMQ setup
######
#  rabbitmq:
#    image: 'bitnami/rabbitmq:latest'
#    environment:
#      RABBITMQ_DEFAULT_USER: "admin"
#      RABBITMQ_DEFAULT_PASS: "admin"
#    ports:
#      - "5672:5672"
#      - "15672:15672"
